### PR TITLE
Add `test-unit` to Gemfile

### PR DESCRIPTION
**Pull request by ericfreese**
Was getting an error running `bundle exec rails console`.

```
activesupport-3.2.22.2/lib/active_support/dependencies.rb:251:in `require': Please add test-unit gem to your Gemfile: `gem 'test-unit', '~> 3.0'` (cannot load such file -- test/unit/testcase) (LoadError)
```

### CODE REVIEW

**Comment by cllns** [comment]
I was able to reproduce this issue locally

**Comment by ericfreese** [comment]
@cllns This may have had something to do with us both running on ruby v2.3.x. On second thought, not sure this is *actually* necessary

**Comment by cllns** [comment]
Ah, yea. `test-unit` was removed from standard library in 2.2.0 it looks like

**Comment by rylanb** [comment]
Ah well we do want it eventually. We will need it when we upgrade?

**Comment by cllns** [comment]
Yea, we'll need it when we upgrade to 2.2 or 2.3 (or higher!). And I don't think it hurts anything when using Ruby 2.1?

**Pull request merged**
