### PR TITLE
Upgrade Ruby from 2.2.6 to 2.3.7

### PR DESCRIPTION
**Pull request by Aupajo**
Ruby 2.2 is [on its last legs](https://www.ruby-lang.org/en/news/2017/04/01/support-of-ruby-2-1-has-ended/):

> We are planning to end the support of the Ruby 2.2 series at the end of March 2018.

Prior to this PR, we were running 2.2.6, which four versions behind the latest patch release for the 2.2 series, 2.2.10. These patch releases include numerous bug fixes and security updates.

Ideally, we'd move all the way to the latest release (2.5.1), but some further changes are going to be necessary to support that. (dependency upgrades). For now, Ruby 2.3.7 is as high as I can take it while leaving the current Gemfile depdencies as they are.

### CODE REVIEW

**Comment by Aupajo** [comment]
@rylanb I was trying to figure that out. Turned out `.travis.yml` wasn't in this branch when I forked it – have rebased and updated it.

Tests are now passing on CI, but Rubocop is failing.

**Comment by rylanb** [comment]
I think the merge conflicts are from your other branches updates that I just merged. Sorry if I did those in the wrong order, there!

**Comment by Aupajo** [comment]
@rylanb No worries. All sorted!

**Comment by rylanb** [comment]
Thanks @Aupajo !! Great work. Excited to be up to Ruby 3!

**Pull request merged**
