### PR TITLE
Add driver waiver form

### PR DESCRIPTION
**Pull request by glen0071**
Added driver waiver form to the app.
Tried to mimic the behavior and design of the existing general waiver form in the app.

### CODE REVIEW

**Comment by eloaverona** [comment]
We'll undo the changes to the schema file. The problem with the Gemlock.file was that some of us are developing on Windows, and the resulting Gemlock.file had platform specific gem versions that we did not want to include. Our solution was to omit the Gemlock.file but as this is not ideal, we are unsure what to do. This seems to be a common problem for people developing on Windows. The only solution we found online was to run `bundle install` in OSX or Linux platform before pushing. Do you have any pointers on what would be the best solution?

**Comment by rylanb** [comment]
Hey @eloaverona I do not have a clear solution for you on that one, you could remove the Gemfile.lock locally and bundle install (or whatever Windows uses), but you would just not commit the removal of the file to the repository. This would allow local development to continue for Windows machines. 

The lock file locks gem versions down so that we don't find issues with gem versions, especially when deploying to production. It is required for the application and cannot be merged with that file removed.

Which gems are not the right versions for Windows?

**Comment by eloaverona** [comment]
@rylanb, thanks for the suggestion! Will we look into it! The Gemfile.lock has the -x64-mingw32 in the end of the version of some of the gems. Here is a full list of the gems:
```
bcrypt (3.1.11-x64-mingw32)
eventmachine (1.2.3-x64-mingw32)
ffi (1.9.18-x64-mingw32)
nokogiri (1.6.7.2-x64-mingw32)
pg (0.18.4-x64-mingw32)
sqlite3 (1.3.12-x64-mingw32)
unf_ext (0.0.7.2-x64-mingw32)
```

**Comment by rylanb** [comment]
@eloaverona have you read through -> http://bundler.io/man/gemfile.5.html#PLATFORMS ?

**Pull request closed without merging**
