### PR TITLE
Add a rake task to populate the database with sample data

### PR DESCRIPTION
**Pull request by ericfreese**
## Overview
Add a rake task to populate the database with sample data. This task can be expanded upon to provide a full set of test data for developers who don't have access to a SQL dump from production.

## Details
- Invoke with `rake db:populate`.
- Will create a new `Region` named "Boulder" and a new `Volunteer` with
email `volunteer@example.com` and password `changeme`.

### CODE REVIEW

**Comment by cllns** [comment]
Any reason to use the custom `rake db:populate` task instead of just filling out `db/seeds.rb` and using `rake db:migrate`?

**Comment by ericfreese** [comment]
@cllns My understanding is that seeds should contain records that need to exist for the system to function correctly in all environments (including production)- things like cell phone carriers, food types, transport type. This task would populate the database with a bunch of dummy data that can be used for dev, but wouldn't be added to production.

**Comment by cllns** [comment]
Cool. I've heard that distinction before too! I want to make a `bin/setup` script for this project eventually, which can run `db:seeds` and `db:populate` too.

What do you think about adding something like [`spec/rails_helper.rb`](https://github.com/boulder-food-rescue/food-rescue-robot/blob/master/spec/rails_helper.rb#L5) has?:
```
abort("The Rails environment is running in production mode!") if Rails.env.production?
```

**Comment by ericfreese** [comment]
> What do you think about adding something like spec/rails_helper.rb has?:

I like. Will add this next time I work on this.

**Comment by mfrost** [comment]
@ericfreese are you looking to add the production failsafe? Ran this locally and it worked as expected. 👍

**Comment by ericfreese** [comment]
Closing this now that we have a sanitized db dump. Will keep the branch around just in case, but this won't be necessary for now.

**Pull request closed without merging**
